# Generated by Django 4.2.7 on 2023-12-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('subtitulo', models.TextField()),
                ('imagem', models.ImageField(upload_to='static/assets/img')),
                ('teconlogias', models.TextField()),
                ('descricao', models.TextField()),
                ('problemas_solucoes', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='CriarProjetos',
        ),
    ]
